#!/usr/bin/env python
#coding:utf-8

from pexpect import pxssh
import getpass

def basic_config():
    """
    需要安装Pexpect模块，测试过程中发现，由于本次编写的工具中用到的是pxssh方法，但是该方法调用了linux的termios模块，此模块没有windows版本的。
    """
    hostname = raw_input("输入要连接的主机IP或者主机名:")
    username = raw_input("输入用户名:")
    password = getpass.getpass("输入密码:")
    ssh_connect = pxssh.pxssh()
    flag = True
    cmd_line = r"[%s@%s]>>>" % (username, hostname)
    usage = """
	通用命令:
	    exit:退出ssh连接会话；
	    help:显示通用命令信息；"""
    try:
        if ssh_connect.login(hostname, username, password):
	    while flag:
	        command = raw_input(cmd_line)
		if command.lower() == "exit":
		    flag = False
		    ssh_connect.logout()
		    print cmd_line + "成功退出ssh终端"
		elif command.lower() == "help":
		    print usage
		    command = raw_input(cmd_line)
		else:		
		    ssh_connect.sendline(command)
		    ssh_connect.prompt()
		    print cmd_line + ssh_connect.before
    except pxssh.ExceptionPxssh, e:
	print e
	return basic_config()
    return


if __name__ == "__main__":
    basic_config()
